# -*- coding: utf-8 -*-
"""modeling.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-ewzBRgBL9Ty7NYceZK_5NmKUbiRLoFW
"""

import numpy as np
from sklearn.pipeline import Pipeline
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from xgboost import XGBClassifier
from sklearn.metrics import accuracy_score, roc_auc_score, confusion_matrix, classification_report

import category_encoders as ce
from sklearn.preprocessing import StandardScaler


def build_base_models():
    models = {
        "Logistic Regression": LogisticRegression(max_iter=2000),
        "Random Forest": RandomForestClassifier(
            n_estimators=400,
            max_depth=6,
            random_state=42
        ),
        "XGBoost": XGBClassifier(
            n_estimators=400,
            learning_rate=0.05,
            max_depth=4,
            subsample=0.8,
            colsample_bytree=0.8,
            eval_metric="logloss",
            random_state=42
        )
    }
    return models


def train_and_evaluate(model_name, model, preprocessor, X_train, y_train, X_test, y_test):
    print(f"\n================= {model_name} =================")

    pipe = Pipeline(steps=[
        ("preprocess", preprocessor),
        ("model", model)
    ])

    pipe.fit(X_train, y_train)

    y_pred = pipe.predict(X_test)
    y_proba = pipe.predict_proba(X_test)[:, 1]

    acc = accuracy_score(y_test, y_pred)
    auc = roc_auc_score(y_test, y_proba)
    cm = confusion_matrix(y_test, y_pred)

    print("Accuracy:", acc)
    print("AUC:", auc)
    print("Confusion Matrix:\n", cm)
    print("Classification Report:\n", classification_report(y_test, y_pred))

    return pipe, auc


def run_all_models(preprocessor, X_train, y_train, X_test, y_test):
    models = build_base_models()
    auc_scores = {}
    trained_pipes = {}

    for name, model in models.items():
        pipe, auc = train_and_evaluate(name, model, preprocessor, X_train, y_train, X_test, y_test)
        auc_scores[name] = auc
        trained_pipes[name] = pipe

    print("\n========== MODEL AUC COMPARISON ==========")
    for name, auc in auc_scores.items():
        print(f"{name}: {auc}")

    best_model_name = max(auc_scores.items(), key=lambda x: x[1])[0]
    best_model_pipe = trained_pipes[best_model_name]

    print(f"\nBest model based on AUC: {best_model_name}")

    return best_model_name, best_model_pipe, auc_scores


def train_woe_logistic(X_train, y_train, X_test, y_test, categorical_features):
    print("\n===== WOE Logistic Regression =====")

    X_train_woe = X_train.copy()
    X_test_woe = X_test.copy()

    woe_encoder = ce.WOEEncoder(cols=categorical_features)
    X_train_woe[categorical_features] = woe_encoder.fit_transform(X_train[categorical_features], y_train)
    X_test_woe[categorical_features] = woe_encoder.transform(XTest[categorical_features])

    scaler = StandardScaler()
    X_train_scaled = scaler.fit_transform(X_train_woe)
    X_test_scaled = scaler.transform(X_test_woe)

    woe_logit = LogisticRegression(max_iter=2000)
    woe_logit.fit(X_train_scaled, y_train)

    y_proba_woe = woe_logit.predict_proba(X_test_scaled)[:, 1]
    auc_woe = roc_auc_score(y_test, y_proba_woe)

    print("AUC (WOE Logistic):", auc_woe)

    return woe_logit, auc_woe, woe_encoder, scaler