# -*- coding: utf-8 -*-
"""risk_metrics

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KYG_RF-LOnH3BkfrpXxdEsEB9wZyMtvf
"""

import pandas as pd

# This function uses my trained model to generate Probability of Default (PD)
# for each customer. It gives me a PD value between 0 and 1.
def compute_pd_from_model(model, X):
    pd_values = model.predict_proba(X)[:, 1]
    return pd.Series(pd_values, index=X.index, name="PD")


# This function adds the PD values back into my main dataframe
# so I can use them later for Expected Loss or segmentation.
def add_pd_column(df, pd_series, col_name="PD"):
    df = df.copy()
    df[col_name] = pd_series
    return df


# Here I calculate Expected Loss (EL = PD × LGD × EAD).
# I use Credit Amount as Exposure at Default and set LGD = 45%.
# This helps me understand the financial risk of each customer.
def calculate_expected_loss(df, pd_col="PD", ead_col="Credit amount",
                            lgd=0.45, el_col="EL"):
    df = df.copy()
    df[el_col] = df[pd_col] * df[ead_col] * lgd
    return df


# This function helps me identify the highest-risk customers.
# It sorts the dataset by EL and returns the top N customers
# who contribute the most expected financial loss.
def get_top_expected_loss_customers(df, n=10,
                                    cols_to_show=None,
                                    el_col="EL"):
    if cols_to_show is None:
        cols_to_show = df.columns.tolist()

    df_sorted = df.sort_values(el_col, ascending=False)
    return df_sorted[cols_to_show].head(n)


# This function creates risk segments (Low, Medium, High)
# based on PD ranges. This helps me group customers by risk level
# and understand the overall portfolio structure.
def create_risk_segments(df, pd_col="PD",
                         bins=[0.0, 0.1, 0.3, 1.0],
                         labels=["Low", "Medium", "High"],
                         segment_col="Risk_Segment"):
    df = df.copy()
    df[segment_col] = pd.cut(df[pd_col], bins=bins, labels=labels, include_lowest=True)
    return df